sigstore/cosign-installer

.github/workflows/test-action.yml

Fix incorrect path and clean up docs in test workflow

---

action.yml

Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

Fix outdated path to custom cosign release signature

---

action.yml

Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

Fix incorrect download URL for custom cosign releases

---

README.md
action.yml

Add GitHub Action branding and update readme to point to the release v0.1.0

---

README.md
action.yml

Signed-off-by: Jake Sanders <jsand@google.com>

update bootstrap and default version to v0.4.0

---

.github/workflows/test-action.yml
action.yml

We might want to cut a v1 of the action, as well
Signed-off-by: Jake Sanders <jsand@google.com>

update cosign bootstrap version to v1.0.0

---

README.md

Signed-off-by: Jake Sanders <jsand@google.com>

update readme for v1.0.0

---

.github/workflows/test-action.yml
action.yml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
based on the conversation in PR #15 
https://github.com/sigstore/cosign-installer/pull/15#pullrequestreview-732782575

test with pre-installed libpcsclite1 package

---

README.md
action.yml

cosign: update to release v1.2.1
N/A
```release-note
cosign: update to release v1.2.1
```

cosign: update to release v1.2.1

---

.github/workflows/test-action.yml
README.md
action.yml

- cosign: update to release v1.3.0
Fixes
```release-note
cosign: update to release v1.3.0
```

cosign: update to release v1.3.0

---

action.yml

use `--` for flags in 1.3.0

---

.github/workflows/test-action.yml
README.md

Upgrade cosign version
Fixes
```release-note
* chore: upgrade cosign version 
* docs: upgrade cosign version 
```
cc: @dekkagaijin

upgrade cosign version

---

README.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes
```release-note
```

docs: replace single dashes with two

---

README.md

The current example workflow fails due to a lack of permissions for checking out the repository. This PR fixes it.

Fix permissions for example workflow

---

README.md
action.yml

update action for v1.4.0 release

---

README.md
action.yml

- update cosign to v1.4.1
n/a
```release-note
update cosign to v1.4.1
```

update cosign to v1.4.1

---

README.md
action.yml

- update cosign action to 1.5.1
n/a
```release-note
update cosign action to 1.5.1
```

update cosign action to 1.5.1

---

.github/workflows/test-action.yml

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

fix yaml indent

---

README.md
action.yml

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

update to v1.5.2

---

README.md

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

update link to security process

---

.github/workflows/test-action.yml
README.md
action.yml

- update action to use cosign release v1.7.1

update action to use cosign release v1.7.1

---

README.md
action.yml

- default cosign to 1.9.0 release

default cosign to 1.9.0 release

---

README.md
action.yml

- update action to default cosign to v1.11.0 release

update action to default cosign to v1.11.0 release

---

.github/dependabot.yml

cleanup dependabot

---

.github/workflows/test-action.yml
README.md
action.yml

bump cosign to v1.12.1

---

README.md
action.yml

bump cosign to v1.13.0

---

README.md
action.yml

- bump cosign install to use release v1.13.1

bump cosign install to use release v1.13.1

---

README.md
action.yml

Setting `v2.0.0` version of `cosign`

v2.0.0 release

---

action.yml

make v2.0.0 release of cosign default version of the cosign-installer action
make cosign v2.0.0 default version
PTAL @cpanato

make cosign v2.0.0 default version

---

README.md

This PR will update the README to help people by using intermediate environment variables avoid having script injection attacks by hackers
fix: update README to use intermediate environment variables to avoid risks of script injection
To get more information: _https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable_

use intermediate environment variables to avoid risks of script injection

---

README.md

add --yes option to cosign sign

---

.github/workflows/test-action.yml

- update job to use latest action release

update job to use latest action release

---

action.yml

fix https://github.com/sigstore/cosign-installer/issues/146

Support the runner context of gitea act

---

.github/workflows/test-action.yml
README.md
action.yml

bump cosign to v2.2.1

---

.github/workflows/test-action.yml

test with latest go version

---

README.md

Update `README.md` with cosign examples that work with multiple tags.
Fixes https://github.com/sigstore/cosign-installer/issues/154

Use examples that work with multiple tags

---

README.md
action.yml

- default cosign install to release v2.2.3

default cosign install to release v2.2.3

---

.github/workflows/test-action.yml

use go 1.22 now

---

action.yml

bump default version to v2.4.0 release

---

README.md
action.yml

bump for latest cosign v2.4.1 release

---

README.md
action.yml

update default version to v2.4.2

bump for cosign v2.4.2 release

---

action.yml

fixes #187 
Makes the installer use cosign v2, when install from "main".
**Testing**
Working in pre-submit that installs from @main.
- https://github.com/sigstore/cosign-installer/actions/runs/14458136103/job/40545536680?pr=186#step:4:247
Make the installer use cosign v2, when install from "main".

install cosign v2 from main

---

README.md
action.yml

- default action install to use release v2.5.1

default action install to use release v2.5.1

---

README.md
action.yml

Update default to v2.5.3
