sigstore/cosign-installer

.github/workflows/test-action.yml, action.yml
This adds support to the user select a version of cosign or use the default one
Based on the comments in the issue, it downloads the hardcoded one, does the checks, and then downloads the custom cosign, and applies the same checks, and replaces it.
Right now it is a bit hard to test with another release because just have one 😄 
Added some GitHub actions to validate the new cases.
Feel free to close this PR if does not makes sense or you don't want that.
_note_: the test actions will fail because the code does not exist in the main branch, but can check the tests here: https://github.com/cpanato/cosign-installer/runs/2218204242?check_suite_focus=true
Followup:
- make a release of this action and publish it to the Github Martkplace
/assign @dlorenc 
Fixes: …
=> feature: add option to select a custom release

action.yml
We'll also need to special case the form of its release artifacts
=> update cosign-installer default version to v0.6.0

action.yml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
I tested it, you can see the results from the link below:
> https://github.com/developer-guy/cosign-installer/actions/runs/1142685296
=> lets use sha256sum instead of shasum -a 256

action.yml
cleanup files after validation, those are not needed after the install
Fixes: https://github.com/sigstore/cosign-installer/issues/21
=> cleanup files after validation

.github/workflows/test-action.yml, action.yml
Install cosign in its own directory and add CI tests to validate if the checkout-ed repo remains clean
Fixes: https://github.com/sigstore/cosign-installer/issues/23
=> install consign in the .cosing directory to not mess with any other directories

README.md, action.yml
- Update cosign to v1.2.0 
release: https://github.com/sigstore/cosign/releases/tag/v1.2.0
=> Update cosign to v1.2.0 

.github/workflows/test-action.yml, README.md
Add permission scope documentation for the GH Action and also set those in the CI
Fixes: https://github.com/sigstore/cosign-installer/issues/26
```release-note
document permission scopes
```
=> adding permission scope

README.md, action.yml
- upgrade cosign to 1.3.1 and prepare for the gh action release
n/a
```release-note
upgrade cosign to 1.3.1 and prepare for the gh action release
```
=> upgrade cosign to 1.3.1 and prepare for the gh action release

.github/workflows/test-action.yml, action.yml
Allows setting a custom dir for binary install
Fixes #36 
-->
```release-note
The following optional inputs:
| Input | Description |
| --- | --- |
| `cosign-release` | `cosign` version to use instead of the default. |
| `install-dir` | `target dir to install `cosign` at. |
```
=> Allow setting a custom install dir

.github/workflows/test-action.yml, README.md, action.yml
Adds support for `macOS` runners as well as different processor architectures for `linux` and `macOS`. I will add `windows` support under a different PR.
Part of #42
* Added support for `macOS` runners 
* Added support for different processor architectures for `linux` and `macOS`
```release-note
```
=> add multiarch support for both linux and macOS runners

README.md
Simplifies the `permissions` in sample workflows.
What we really want is `permissions: none-all`, but that doesn't exist. Instead, explicitly setting the permissions for any scope, sets the permissions for all other scopes to `none`[^1]
N/A
```release-note
NONE
```
[^1]: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions
=> docs: simplify permissions in workflow examples

.github/workflows/test-action.yml, README.md, action.yml
Signed-off-by: Bob Callaway <bob.callaway@gmail.com>
Fixes
```release-note
```
=> add support for windows runners

.github/workflows/test-action.yml
Addressing https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
data from running `scorecard --show-details --repo=https://github.com/sigstore/cosign-installer/ --checks Pinned-Dependencies --format json`:
```
{
"date": "2022-01-12",
"repo": {
"name": "github.com/sigstore/cosign-installer",
"commit": "fb055c05fad51114678995df1accc3adf0525baf"
},
"scorecard": {
"version": "b79b3c3",
"commit": "b79b3c357c99a38afabbdbdab1047c15c0db4afd"
},
"score": 8,
"checks": [
{
"details": [
"Warn: GitHub-owned action not pinned by hash: .github/workflows/test-action.yml:24",
"Warn: GitHub-owned action not pinned by hash: .github/workflows/test-action.yml:58",
"Warn: third-party action not pinned by hash: .github/workflows/test-action.yml:60",
"Warn: GitHub-owned action not …
```
=> pin github actions in test harness

.github/workflows/test-action.yml, README.md, action.yml
feat: add install with go support, fix flags
Fixes #45 
```release-note
feat: add install with go support, fix flags
```
=> feat: add install with go support, fix flags

.github/workflows/test-action.yml, README.md, action.yml
- update action to default cosing to v1.6.0 release
n/a
```release-note
update action to default cosing to v1.6.0 release
```
=> update action to default cosing to v1.6.0 release

.github/workflows/test-action.yml, README.md
GitHub actions now has a 'none-all' shorthand[^1]
> You can use the following syntax to disable permissions for all of the available scopes:
> 
> ```
> permissions: {}
> 
This is the same behaviour as before, but is more intuitive than `actions: none`
N/A
```release-note
NONE
```
[^1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
=> docs: update permissions to use new none format

README.md, action.yml
- update action to use cosign v1.7.2 by default
n/a
```release-note
NONE
```
=> update action to use cosign v1.7.2 by default

README.md, action.yml
- update cosign to use 1.8.0 as default
n/a
```release-note
NONE
```
=> update cosign to use 1.8.0 as default

action.yml
Signed-off-by: raulcabello <raul.cabello@suse.com>
Keep `.exe` extension in cosign for Windows. Cosign is not working as expected because the extension is removed. It does nothing when executing a cosign command, and it does not display any error or output.
Fixes #78 
```release-note
NONE
```
=> keep .exe extension in cosign for windows

.github/workflows/test-action.yml, action.yml
We cannot use `install-dir`s like `/usr/bin/cosign` right now because
this would cause an permission denied error. To be able to use those
paths we have to run `mv` and `chmod` via root.
None
```release-note
Fixed `install-dir` locations to work when they require root access (for example `/usr/bin/cosign`.
```
=> `sudo` mv the cosign binary to the `install-dir`

.github/workflows/test-action.yml, README.md, action.yml
Adds optional input `use-sudo` that can be set to `true` in the case that `install-dir` requires sudo privs. The reason for this is that always using `sudo` actually broke our `self-hosted` runners since the user the runner runs as doesn't have sudo privs by security design.
Fixes https://github.com/sigstore/cosign-installer/issues/85
```release-note
* adds `use-sudo` optional input which defaults to false
```
=> add use-sudo optional parameter defaulting to false. Fixes: #85

.github/workflows/test-action.yml, action.yml
- update cosign to use v1.10.0 release
- enable go install test
`n/a`
`n/a`
=> Update action to install cosign 1.10.0 by default

.github/workflows/test-action.yml, README.md, action.yml
Signed-off-by: Kenny Leung <kleung@chainguard.dev>
update default version of cosign to latest, 1.10.1
update default version of cosign to latest, 1.10.1
=> update default cosign version to 1.10.1

action.yml
=> default cosign to v1.11.1

action.yml
Signed-off-by: Hector Fernandez <hector@chainguard.dev>
Add logs when downloading the public key to trace all the different files used before verification.
=> test: add logs when downloading the public keys

README.md, action.yml
Signed-off-by: Hector Fernandez <hector@chainguard.dev>
Enable installing release candidates. I am starting to use cosign v2 release candidate and I could not test it using the cosign-installer due to the regular expressions and other settings.
Please, let me know if we want to enable the installation of release candidates. Otherwise I am happy to close this PR.
=> Add support to install v2 and any other cosign release candidate

README.md
Version 2.0 of cosign is asking users to confirm that information is stored in public transparency logs. This interactive interaction does not work in automated CI pipelines like GitHub actions and breaks builds that are now starting to use 2.0. Adding --yes removes the required user interaction and enables automated builds again.
NONE
This PR updates the documentation in this repo. I could not find anything related to GitHub Actions in docs.sigstore.dev
=> add --yes to example workflow

action.yml
It seems there's a typo in the ARM64 case. 
The `desired_cosign_filename` variable is set to `_amd64`. This small patch fixes it.
Closes #112
=> Fix aarch64 action run

.github/workflows/test-action.yml, README.md, action.yml
=> default cosign to v2.0.1

README.md
I saw that cosign sign command uses the $TAGS variable outputted by another action named metadata-action provided by Docker but as we know that we should rely upon the digests not tags, so I switched it with digest using the same example provided by GitHub, thanks to @mattmoor!
> _https://github.com/actions/starter-workflows/blob/87fbe43482b4d29e522c97acec91fddeeb2b5a88/ci/docker-publish.yml#L96_
=> we should rely upon the digests not the tags, typos

README.md
Removes the experimental warning which seems to be outdated.
See sigstore/cosign-installer#120
NONE
NONE
=> Remove warning about signing GitHub OIDC Tokens being experimental

action.yml
Swap downloading cosign from GCS bucket to GitHub to speed up downloads and remove external dependency.
=> download cosign releases from GitHub rather than GCS

README.md
Remove xargs call in the keyless signing example as cosign now detects the non-interactive mode.
Fixes: #131 
This is a doc change :)
=> Update action example for keyless signing as xarg is not required

.github/workflows/test-action.yml, README.md, action.yml
- bump cosign to default to release v2.1.0 and update docs
=> bump cosign to default to release v2.1.0 and update docs

README.md, action.yml
=> default cosign to v2.1.1

README.md
Fix missing identifier for build and publish docker hub step on Readme
=> Fix build and push step Readme missing id

.github/workflows/test-action.yml, action.yml
=> bump cosign to v2.2.0

README.md, action.yml
- update action to use latest cosign v2.2.2
=> update action to use latest cosign v2.2.2

.github/workflows/test-action.yml, README.md, action.yml
=> bump default version to v2.2.4, prep for v3.5.0 release

.github/workflows/test-action.yml, action.yml
this tests the action against all published releases
also verifies inclusion in rekor
=> test action against all non-rc releases, verify entry in rekor log

README.md, action.yml
- bump cosign install to use release v2.5.0 as default
=> bump cosign install to use release v2.5.0 as default
